using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AppDimens.Maui.SourceGen;

[Generator(LanguageNames.CSharp)]
public sealed class DimenSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("Dimen.g.cs", SourceText.From(GenerateDimenClass(), Encoding.UTF8));
        });
    }

    private static string GenerateDimenClass()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("namespace AppDimens.Maui.Generated;");
        sb.AppendLine("public static partial class Dimen");
        sb.AppendLine("{");

        for (var i = 1; i <= 96; i++)
        {
            sb.AppendLine($"    public static double _{i}sdp => global::AppDimens.Maui.AppDimensSdps.Sdp({i});");
            sb.AppendLine($"    public static double _{i}ssp => global::AppDimens.Maui.AppDimensSdps.Ssp({i});");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
