<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>AppDimens.Net.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AppDimens.Net.Sdk\AppDimens.Net.Sdk.csproj" />
    <ProjectReference Include="..\..\src\AppDimens.Net.Maui\AppDimens.Net.Maui.csproj" />
    <ProjectReference Include="..\..\benchlab\AppDimens.BenchLab\AppDimens.BenchLab.Core\AppDimens.BenchLab.Core.csproj" />
  </ItemGroup>

</Project>
