<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AppDimens.WebDemo</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <BlazorEnableCompression>false</BlazorEnableCompression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.11" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AppDimens.Net\AppDimens.Net.csproj" />
    <ProjectReference Include="..\..\src\AppDimens.Net.Auto\AppDimens.Net.Auto.csproj" />
    <ProjectReference Include="..\..\src\AppDimens.Net.Density\AppDimens.Net.Density.csproj" />
    <ProjectReference Include="..\..\src\AppDimens.Net.Diagonal\AppDimens.Net.Diagonal.csproj" />
    <ProjectReference Include="..\..\src\AppDimens.Net.Percent\AppDimens.Net.Percent.csproj" />
    <ProjectReference Include="..\..\src\AppDimens.Net.Fluid\AppDimens.Net.Fluid.csproj" />
    <ProjectReference Include="..\..\src\AppDimens.Net.Resize\AppDimens.Net.Resize.csproj" />
  </ItemGroup>

</Project>
