{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.bodenberg",
    "module": "appdimens-dynamic-resize",
    "version": "3.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.bodenberg",
          "module": "appdimens-dynamic",
          "version": {
            "requires": "3.1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "appdimens-dynamic-resize-3.1.9.aar",
          "url": "appdimens-dynamic-resize-3.1.9.aar",
          "size": 24418,
          "sha512": "427e7cc4d642ee7dc7900c949470e1b462878e24d7487d738503595f0f8a19b2eac91cb09fa97c18fa9b46c37d4aa1496de5a261283b3270367f8091e2c2ccd1",
          "sha256": "512837ea03e9fd9bdc99b46c1173b4556647b04c32d4d08d1702ceb4caf82eae",
          "sha1": "5d795ab86fbe7b7feac91eb598361e6d5062090b",
          "md5": "8214c2e16b80dfca247dd889c071f854"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.github.bodenberg",
          "module": "appdimens-dynamic",
          "version": {
            "requires": "3.1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "appdimens-dynamic-resize-3.1.9.aar",
          "url": "appdimens-dynamic-resize-3.1.9.aar",
          "size": 24418,
          "sha512": "427e7cc4d642ee7dc7900c949470e1b462878e24d7487d738503595f0f8a19b2eac91cb09fa97c18fa9b46c37d4aa1496de5a261283b3270367f8091e2c2ccd1",
          "sha256": "512837ea03e9fd9bdc99b46c1173b4556647b04c32d4d08d1702ceb4caf82eae",
          "sha1": "5d795ab86fbe7b7feac91eb598361e6d5062090b",
          "md5": "8214c2e16b80dfca247dd889c071f854"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appdimens-dynamic-resize-3.1.9-sources.jar",
          "url": "appdimens-dynamic-resize-3.1.9-sources.jar",
          "size": 10631,
          "sha512": "5652d4a935ee24ce1445db547e730e17d5607ce4c0eb4beb4a0881ec62951df666603a20dc73796c8d9a9f80d0f292db9821239d938503899a85c114dbc24d3c",
          "sha256": "db3494a84efdb36c65c4fb29da36678ab5800eadd40c4d8563a91d7d7240f521",
          "sha1": "388d80c82034b49d9502406d3beaf922e55e50a7",
          "md5": "9b527275ee3e6999edb6bc816ce28e29"
        }
      ]
    }
  ]
}
