{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.bodenberg",
    "module": "appdimens-dynamic-power",
    "version": "3.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.bodenberg",
          "module": "appdimens-dynamic",
          "version": {
            "requires": "3.1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "appdimens-dynamic-power-3.1.9.aar",
          "url": "appdimens-dynamic-power-3.1.9.aar",
          "size": 132940,
          "sha512": "0247ee6df2c5dd2a8e0f30025a03677362bf7c02d972dcf6adcaf88f07baf783c0d52e8225f58a2166cc298daefcc33318307c5e0e5a30f8c5da456df6fecb50",
          "sha256": "575f153442654972174f5595470eb5e044ec6b717ebdad6f9e6afc23f91cf818",
          "sha1": "699ea808a1a92fab11f4fdd92bd048ae9485c00c",
          "md5": "bf4c53dc70d0797e6d33f6ac3f2c5f56"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.github.bodenberg",
          "module": "appdimens-dynamic",
          "version": {
            "requires": "3.1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "appdimens-dynamic-power-3.1.9.aar",
          "url": "appdimens-dynamic-power-3.1.9.aar",
          "size": 132940,
          "sha512": "0247ee6df2c5dd2a8e0f30025a03677362bf7c02d972dcf6adcaf88f07baf783c0d52e8225f58a2166cc298daefcc33318307c5e0e5a30f8c5da456df6fecb50",
          "sha256": "575f153442654972174f5595470eb5e044ec6b717ebdad6f9e6afc23f91cf818",
          "sha1": "699ea808a1a92fab11f4fdd92bd048ae9485c00c",
          "md5": "bf4c53dc70d0797e6d33f6ac3f2c5f56"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appdimens-dynamic-power-3.1.9-sources.jar",
          "url": "appdimens-dynamic-power-3.1.9-sources.jar",
          "size": 56464,
          "sha512": "3a05b682c1b752ed7aab5c2129989f82b6a6d506226879c8c591e9a86bd598585a63844a43d5b285fda2fa38dc38c94e0e07bab05a4c29b7f30798b263752463",
          "sha256": "216bdda8020c97e0b12bd1e0e4941d9b6d288b73ff0de595126ca9cd6ab1eea5",
          "sha1": "663a7c7cf752e0cc990921e321ef4909ecd47962",
          "md5": "1218f19f9ab86aa1f2a9a81e4bdfd091"
        }
      ]
    }
  ]
}
