{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.bodenberg",
    "module": "appdimens-dynamic-diagonal",
    "version": "3.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.bodenberg",
          "module": "appdimens-dynamic",
          "version": {
            "requires": "3.1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "appdimens-dynamic-diagonal-3.1.9.aar",
          "url": "appdimens-dynamic-diagonal-3.1.9.aar",
          "size": 132455,
          "sha512": "c39a6157e8e76c1a29f72d76575333fb65a0113f3ffbad8bcc98259eefebe3bde202dc550a493437f3d366d619550acd433b301e699cc446dc37cbcb8338f1b7",
          "sha256": "f4b64fad50065d8c577a675ac62531cbb529923a799673f6b16c3500ea182e6e",
          "sha1": "aca5e0362c047a03a69e6911defb51e96c636c55",
          "md5": "ffa02287fc77c3155edbfd18039e744d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.github.bodenberg",
          "module": "appdimens-dynamic",
          "version": {
            "requires": "3.1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "appdimens-dynamic-diagonal-3.1.9.aar",
          "url": "appdimens-dynamic-diagonal-3.1.9.aar",
          "size": 132455,
          "sha512": "c39a6157e8e76c1a29f72d76575333fb65a0113f3ffbad8bcc98259eefebe3bde202dc550a493437f3d366d619550acd433b301e699cc446dc37cbcb8338f1b7",
          "sha256": "f4b64fad50065d8c577a675ac62531cbb529923a799673f6b16c3500ea182e6e",
          "sha1": "aca5e0362c047a03a69e6911defb51e96c636c55",
          "md5": "ffa02287fc77c3155edbfd18039e744d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appdimens-dynamic-diagonal-3.1.9-sources.jar",
          "url": "appdimens-dynamic-diagonal-3.1.9-sources.jar",
          "size": 56320,
          "sha512": "b4fa007b33b5fc053b23c626e9ef465e644496ccdcf0118a1c3276204d1b07328207ed925efe33a1a3c4b7e63e9aeb1a38f8cf91ca58e6e0121624d56673bf73",
          "sha256": "493cefbdbb0dd1b56cd304690b46c4e2365470e23dbc34b1fbfbf0c8b9ec0fb1",
          "sha1": "144b9c0fe4b7b5d3a89bebadc37128563986b512",
          "md5": "7fc6dac6b0bc9d8bbaf0e8ce961f205d"
        }
      ]
    }
  ]
}
